name: CI/CD Pipeline

on:
  push:
    branches:
      - main #main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          cd backend  # Navigate to the backend directory where requirements.txt is located
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Migrations
        run: |
          cd backend  # Ensure we're in the backend directory
          python manage.py migrate  # Apply database migrations

      - name: Run tests
        run: |
          cd backend  # Navigate to the backend directory
          python manage.py test
