name: Vercel Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python for Backend
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Backend Dependencies
        working-directory: TODO-APP/backend
        run: |
          pip install -r TODO-APP/backend/requirements.txt

      - name: Deploy to Vercel
        run: |
          curl -fsSL https://vercel.com/download -o vercel.tar.gz
          tar -xzf vercel.tar.gz
          sudo mv vercel /usr/local/bin
          vercel login ${{ secrets.VERCEL_EMAIL }}
          vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }}
